name: CBWrapper-CraftBook Compat
main: misson20000.plugins.cbwrapper.CBWrapper
version: 1.6 [Bukkit 1.7.2-R0.3]

commands:
  cw:
    description: For CraftBook compatibility. This will forward commands as a dummy player, for command blocks
    usage: /cw [-o ~x ~y ~z] [-u username] (command) [args]
    permission: cbwrapper.cb
    permission-message: You don't have cbwrapper.cb permission